Hashing: merkle_verify_proof
lambdaclass/leo_stdlib pull request #12
Opened 2022-06-28 17:24 UTC by mationorato

Add merkle proof verifier to hashing library

- [x] code merkle_verify_proof() function
- [x] add documentation
- [x] add unit tests

2022-06-29 21:01 UTC, pablodeymo requested changes

2022-06-29 21:01 UTC, pablodeymo commented on README.md
> +merkle_verify_proof(leave:field, proof: [field;8], path_index: [bool;n], root: field) -> bool
I think there is a typo in the name of the argument `leave`

2022-06-29 21:07 UTC, Loco1982 requested changes
Minor spelling changes

2022-06-29 21:07 UTC, Loco1982 commented on std/src/main.leo
> +    console.assert(!verify_proof(leave,proof,bad_path, root));
```suggestion
    console.assert(!verify_proof(leave, proof, bad_path, root));
```

2022-06-29 21:07 UTC, Loco1982 commented on std/src/hashing.leo
> +            element = poseidon(proof[i],element);
```suggestion
            element = poseidon(proof[i], element);
```

2022-06-29 21:07 UTC, Loco1982 commented on std/src/main.leo
> +    let path: [bool;3] = [false,false,false];
```suggestion
    let path: [bool;3] = [false, false, false];
```

2022-06-29 21:07 UTC, Loco1982 commented on std/src/main.leo
> +    let bad_path: [bool;3] = [true,true,true];
```suggestion
    let bad_path: [bool;3] = [true, true, true];
```

2022-06-29 21:07 UTC, Loco1982 commented on std/src/main.leo
> +    console.assert(!verify_proof(leave,proof,path, bad_root));
```suggestion
    console.assert(!verify_proof(leave, proof, path, bad_root));
```

2022-06-29 21:07 UTC, Loco1982 commented on std/src/main.leo
> +    let path2: [bool;3] = [true,false,true];
```suggestion
    let path2: [bool;3] = [true, false, true];
```

2022-06-30 14:27 UTC, MauroToscano commented on README.md
> +merkle_verify_proof(leave:field, proof: [field;8], path_index: [bool;n], root: field) -> bool
You are right! I'm fixing it

2022-06-30 15:44 UTC, merged